export const FETCH_UPCOMING_APPOINTS = "FETCH_UPCOMING_APPOINTS";
export const FETCH_UPCOMING_APPOINTS_FINISHED =
  "FETCH_UPCOMING_APPOINTS_FINISHED";

export const FETCH_HISTORY_APPOINTS = "FETCH_HISTORY_APPOINTS";
export const FETCH_HISTORY_APPOINTS_FINISHED =
  "FETCH_HISTORY_APPOINTS_FINISHED";
