export const GET_PROFILE_DATA = "GET_PROFILE_DATA";
export const SET_PROFILE_DATA = "SET_PROFILE_DATA";
export const GET_PROFILE_FAILED = "GET_PROFILE_FAILED";

export const ON_DELETE_USER = "ON_DELETE_USER";
export const ON_DELETE_USER_FINISHED = "ON_DELETE_USER_FINISHED";

export const ON_LOG_OUT = "ON_LOG_OUT";
export const ON_LOG_OUT_FINISHED = "ON_LOG_OUT_FINISHED";

export const ON_CHANGE_PROFILE_DATA = "ON_CHANGE_PROFILE_DATA";

export const TOGGLE_DELETE_ACCOUNT = "TOGGLE_DELETE_ACCOUNT";
